<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PendaftaranSeeder extends Seeder
{
    public function run()
    {
        $data = [
            // DATA TA 2024/2025
            [
                'nama_siswa' => 'ABIZAR MAHADIRGA ZAFRAN',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_tgl_lahir' => 'SLEMAN, 2017-10-01',
                'agama' => 'Islam',
                'alamat' => 'KALIMANJUNG, RT 1, RW 31, AMBARKETAWANG, Gamping',
                'nama_ayah' => 'WAJINO',
                'pendidikan_terakhir_ayah' => 'SMA / sederajat',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'nama_ibu' => 'RATNA WIDARYATI',
                'pendidikan_terakhir_ibu' => 'SMA / sederajat',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'asal_sekolah' => '-', // Tambahkan ini
                'status' => 'Diterima',
            ],
            [
                'nama_siswa' => 'ANANDA ADELYA PUTRI',
                'jenis_kelamin' => 'Perempuan',
                'tempat_tgl_lahir' => 'SLEMAN, 2017-07-15',
                'agama' => 'Islam',
                'alamat' => 'KALIMANJUNG, RT 1, RW 3, AMBARKETAWANG, Gamping',
                'nama_ayah' => 'M.JAINUDIN',
                'pendidikan_terakhir_ayah' => 'SMP / sederajat',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'nama_ibu' => 'AYU NOVITA SARI',
                'pendidikan_terakhir_ibu' => 'SMA / sederajat',
                'pekerjaan_ibu' => 'Pedagang Kecil',
                'asal_sekolah' => '-', // Tambahkan ini
                'status' => 'Diterima',
            ],
            [
                'nama_siswa' => 'ARFAN AKBAR ALFARIZI',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_tgl_lahir' => 'SLEMAN, 2017-09-01',
                'agama' => 'Islam',
                'alamat' => 'CIBUK LOR I, RT 2, RW 18, Margoluwih, Seyegan',
                'nama_ayah' => 'SOLEH HARYADI',
                'pendidikan_terakhir_ayah' => 'SMA / sederajat',
                'pekerjaan_ayah' => 'Buruh',
                'nama_ibu' => 'ESTI SUSANTI',
                'pendidikan_terakhir_ibu' => 'SMA / sederajat',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'asal_sekolah' => '-', // Tambahkan ini
                'status' => 'Diterima',
            ],
            // DATA TA 2023/2024
            [
                'nama_siswa' => 'AFFAN PRADIPTA WIRATAMA',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_tgl_lahir' => 'Sleman, 2016-03-11',
                'agama' => 'Islam',
                'alamat' => 'Kalimanjung, RT 4, RW 32, Ambarketawang, Gamping',
                'nama_ayah' => 'MARGONO YUDI PRATAMA',
                'pendidikan_terakhir_ayah' => 'SMA / sederajat',
                'pekerjaan_ayah' => 'Buruh',
                'nama_ibu' => 'Susi Sutanti',
                'pendidikan_terakhir_ibu' => 'SMP / sederajat',
                'pekerjaan_ibu' => 'Buruh',
                'asal_sekolah' => '-',
                'status' => 'Diterima',
            ],
            [
                'nama_siswa' => 'ALBY FATHARIAN DESASTA',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_tgl_lahir' => 'Yogyakarta, 2016-12-31',
                'agama' => 'Islam',
                'alamat' => 'Donotirto, RT 7, RW 0, Bangunjiwo, Kasihan',
                'nama_ayah' => 'Agus Supriyatin',
                'pendidikan_terakhir_ayah' => 'S1',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'nama_ibu' => 'Triana Listari',
                'pendidikan_terakhir_ibu' => 'D2',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'asal_sekolah' => '-',
                'status' => 'Diterima',
            ],
            [
                'nama_siswa' => 'ALBY TEGAR WIBOWO',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_tgl_lahir' => 'SLEMAN, 2016-06-13',
                'agama' => 'Islam',
                'alamat' => 'KALIMANJUNG, RT 7, RW 33, Ambarketawang, Gamping',
                'nama_ayah' => 'Timur Ari Wibowo',
                'pendidikan_terakhir_ayah' => 'SMA / sederajat',
                'pekerjaan_ayah' => 'PNS/TNI/Polri',
                'nama_ibu' => 'FITRI APRIAWATI',
                'pendidikan_terakhir_ibu' => 'D3',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'asal_sekolah' => '-',
                'status' => 'Diterima',
            ],
            // DATA TA 2022/2023
            [
                'nama_siswa' => 'ABHAR RIFA',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_tgl_lahir' => 'Bantul, 2015-06-09',
                'agama' => 'Islam',
                'alamat' => 'Kembang, RT 4, RW 0, Tamantirto, Kasihan',
                'nama_ayah' => 'Sugianto',
                'pendidikan_terakhir_ayah' => 'SMP / sederajat',
                'pekerjaan_ayah' => 'Wiraswasta',
                'nama_ibu' => 'ELITA HANDRIANI',
                'pendidikan_terakhir_ibu' => 'SMA / sederajat',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'asal_sekolah' => '-',
                'status' => 'Diterima',
            ],
            [
                'nama_siswa' => 'AISYAH PUSPA RINJANI',
                'jenis_kelamin' => 'Perempuan',
                'tempat_tgl_lahir' => 'BANTUL, 2015-08-22',
                'agama' => 'Islam',
                'alamat' => 'GANGIN, RT 2, RW 0, TAMANTIRTO, Kasihan',
                'nama_ayah' => 'APRILIAN BUDIMAN',
                'pendidikan_terakhir_ayah' => 'SMA / sederajat',
                'pekerjaan_ayah' => 'Buruh',
                'nama_ibu' => 'SRI WAHYUTI',
                'pendidikan_terakhir_ibu' => 'SMA / sederajat',
                'pekerjaan_ibu' => 'Buruh',
                'asal_sekolah' => '-',
                'status' => 'Diterima',
            ],
            [
                'nama_siswa' => 'ALVIN NUR ROKHIM',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_tgl_lahir' => 'Sleman, 2015-11-20',
                'agama' => 'Islam',
                'alamat' => 'Kalimanjung, RT 4, RW 32, Ambarketawang, Gamping',
                'nama_ayah' => 'Ari Setyawan',
                'pendidikan_terakhir_ayah' => 'SMP / sederajat',
                'pekerjaan_ayah' => 'Buruh',
                'nama_ibu' => 'Dwi Astuti',
                'pendidikan_terakhir_ibu' => 'SMP / sederajat',
                'pekerjaan_ibu' => 'Buruh',
                'asal_sekolah' => '-',
                'status' => 'Diterima',
            ],
            [
                'nama_siswa' => 'AQILA NAZHIRA AFIN',
                'jenis_kelamin' => 'Perempuan',
                'tempat_tgl_lahir' => 'Sleman, 2015-10-18',
                'agama' => 'Islam',
                'alamat' => 'Tlogo, RT 2, RW 27, Ambarketawang, Gamping',
                'nama_ayah' => 'Ferry Setyawan',
                'pendidikan_terakhir_ayah' => 'S1',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'nama_ibu' => 'Noviana Tri Astuti',
                'pendidikan_terakhir_ibu' => 'S1',
                'pekerjaan_ibu' => 'Karyawan Swasta',
                'asal_sekolah' => '-',
                'status' => 'Diterima',
            ],
            [
                'nama_siswa' => 'ATHAYA NAILA PUTRI',
                'jenis_kelamin' => 'Perempuan',
                'tempat_tgl_lahir' => 'SLEMAN, 2015-10-02',
                'agama' => 'Islam',
                'alamat' => 'KALIMANJUNG, RT 3, RW 31, Ambarketawang, Gamping',
                'nama_ayah' => 'Aris Triyanto',
                'pendidikan_terakhir_ayah' => 'SMA / sederajat',
                'pekerjaan_ayah' => 'Wiraswasta',
                'nama_ibu' => 'Heni Purwanti',
                'pendidikan_terakhir_ibu' => 'SMA / sederajat',
                'pekerjaan_ibu' => 'Karyawan Swasta',
                'asal_sekolah' => '-',
                'status' => 'Diterima',
            ],
            [
                'nama_siswa' => 'AZZAM KHAIRY AL-FATIH',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_tgl_lahir' => 'BANTUL, 2015-12-04',
                'agama' => 'Islam',
                'alamat' => 'GEBLAGAN, RT 2, RW 0, TAMANTIRTO, Kasihan',
                'nama_ayah' => 'FEBRY KURNIAWAN',
                'pendidikan_terakhir_ayah' => 'D3',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'nama_ibu' => 'SITI FATIMAH',
                'pendidikan_terakhir_ibu' => 'SMA / sederajat',
                'pekerjaan_ibu' => 'Karyawan Swasta',
                'asal_sekolah' => '-',
                'status' => 'Diterima',
            ],
            [
                'nama_siswa' => 'KHOLID SAIFULLAH FAUZI',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_tgl_lahir' => 'Pamekasan, 2017-10-08',
                'agama' => 'Islam',
                'alamat' => 'DSN DONGGADUNG DAJAH, RT 0, RW 0, Tanjung, Pegantenan',
                'nama_ayah' => 'MOH FAUZI',
                'pendidikan_terakhir_ayah' => 'SMP / sederajat',
                'pekerjaan_ayah' => 'Wiraswasta',
                'nama_ibu' => 'MUSLIHAH',
                'pendidikan_terakhir_ibu' => 'SMP / sederajat',
                'pekerjaan_ibu' => 'Petani',
                'asal_sekolah' => '-',
                'status' => 'Diterima',
            ],
            [
                'nama_siswa' => 'MAIZA ASHA AYUDISA SEPTYA',
                'jenis_kelamin' => 'Perempuan',
                'tempat_tgl_lahir' => 'BANTUL, 2017-09-19',
                'agama' => 'Islam',
                'alamat' => 'NGEBEL, RT 8, RW 0, Tamantirto, Kasihan',
                'nama_ayah' => 'HARTONO',
                'pendidikan_terakhir_ayah' => 'SMP / sederajat',
                'pekerjaan_ayah' => 'Buruh',
                'nama_ibu' => 'TRI MARNI ASIH',
                'pendidikan_terakhir_ibu' => 'SMA / sederajat',
                'pekerjaan_ibu' => 'Karyawan Swasta',
                'asal_sekolah' => '-',
                'status' => 'Diterima',
            ],
            [
                'nama_siswa' => 'MUHAMMAD TEGAR WICAKSONO',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_tgl_lahir' => 'Sleman, 2017-07-10',
                'agama' => 'Islam',
                'alamat' => 'Kalimanjung, RT 6, RW 33, Ambarketawang, Gamping',
                'nama_ayah' => 'Hariawan',
                'pendidikan_terakhir_ayah' => 'SMA / sederajat',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'nama_ibu' => 'Ilsa Vilani',
                'pendidikan_terakhir_ibu' => 'SMP / sederajat',
                'pekerjaan_ibu' => 'Tidak bekerja',
                'asal_sekolah' => '-',
                'status' => 'Diterima',
            ],
        ];

        foreach ($data as $item) {
            DB::table('pendaftaran')->insert(array_merge($item, [
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]));
        }
    }
}